#
# Toplevel Makefile
# PLEASE look at the subdirectories!
# There are configs to do! Especially in driver/
#
all:
	(cd driver; make)
	(cd tools/proclcd; make)
	(cd tools/graphics; make)
	(cd tools/lcdtime; make)

clean:
	(cd driver; make clean)
	(cd tools/proclcd; make clean)
	(cd tools/graphics; make clean)
	(cd tools/lcdtime; make clean)
